### PR TITLE
aggs: remove valueLabels property

### PR DESCRIPTION
**Pull request by zzacharo**
* You can override the `agg.bucket` label by injecting a `label` key to
  the `agg.buckets` items

### CODE REVIEW

**Review by ntarocco — APPROVED** [review]
LGTM! I saw/heard that you were opting for a kind of a template, maybe in the future it could be a good idea if you want to do something like `<label (count)>`

**Comment by lnielsen** [comment]
Shouldn't the count be in a separate element somehow so we can do these round circles around the numbers:
Screenshot 2020-10-20 at 15 55 04

**Comment by zzacharo** [comment]
@ntarocco @lnielsen if you want I can amend this PR with a `template` prop, so what @lnielsen show can be feasible!

**Comment by zzacharo** [comment]
@lnielsen For the count, we will override this in `invenio-app-rdm` similar to https://github.com/inveniosoftware/react-invenio-app-ils/blob/75f1faf53b973c2a44d72905115513ffc250730b/src/lib/modules/SearchControls/overridden/CardBucketAggregationValueElement.js#L5

**Pull request merged**
